#!/bin/sh

# Set these paths appropriately

BIN="/home/e20150004937/Documents/Master/S3/TALN/ProjetJDM/ProjetJDM/projetJDM/bin"
CMD="/home/e20150004937/Documents/Master/S3/TALN/ProjetJDM/ProjetJDM/projetJDM/cmd"
LIB="/home/e20150004937/Documents/Master/S3/TALN/ProjetJDM/ProjetJDM/projetJDM/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
