#!/bin/sh

# Set these paths appropriately

BIN="/home/e20150004937/Documents/Master/S3/TALN/ProjetJDM/ProjetJDM/projetJDM/bin"
CMD="/home/e20150004937/Documents/Master/S3/TALN/ProjetJDM/ProjetJDM/projetJDM/cmd"
LIB="/home/e20150004937/Documents/Master/S3/TALN/ProjetJDM/ProjetJDM/projetJDM/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/catalan-abbreviations
PARFILE=${LIB}/catalan.par

$TOKENIZER -c -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
